### ISSUE TITLE
G&B checklist

### ISSUE THREAD

**Issue by manegame** [manegame/sophie-hardeman#21]
- [x] Suggestions For You can be permanent (see sketch)
- [x] Do not contact me.. also permanent (see sketch)
- [x] ‘Video’ btn is now showing next to ‘lookbook’ instead of underneat
- [x] Image top margin always the same, align ‘collections’ with image (see sketch)
- [x] Page titles can be a bit smaller on all pages (Jobs, Contact etc, same as collection titles)
- [x] Stockist layout similar to about section: shops on the left menu, page shows image of shop and description text (ref #15 )
- [x] Video bigger (see sketch)
- [x] Gallery slider still not function or showing on some pages (ref #20 )
- [x] Rouge66 on top of list
- [x] highlight side on scroll (check animated-scrollto)
- [x] side bar (ref #11 )

OPTIONAL
- [ ] With print option gallery disappears
